### ISSUE TITLE
Broadcast View dark line

### ISSUE THREAD

**Issue by Zehir** [codemann8/alttpr_codetracker_codemann8#26]
Hello, I have an issue with the boradcast view in the "Map Tracker" mode.

There is a dark line on the dark world dungeon name (red arrow) and some gray margin on each side (10px left, 5px top, 15px right, 10px bottom).

![image](https://user-images.githubusercontent.com/845225/118379418-7bd53380-b5da-11eb-835b-39212d2ff531.png)

Are these behaviors expected?

Thanks

**Comment by codemann8** [comment]
Fixed
