### ISSUE TITLE
Medallion logic

### ISSUE THREAD

**Issue by Zehir** [codemann8/alttpr_codetracker_codemann8#27]
Hi, I have a quick question about Medallion logic.
If I have the 3 of them, MM and TR should be marked as accesible even if I don't say who open what. If I have them all I can open MM and TR.
The problem if that the tracker expect to select the correct Medallion of each dungeon. But at a time I could not know which one is the correct one but I know what I can open it

**Comment by codemann8** [comment]
The logic already considers this scenario. Also, I invite you to the Discord server where there is more community involvement and discussion of such things. A link is found on the Readme on the main GitHub page.
