### ISSUE TITLE
Spectacle rock - Cave

### ISSUE THREAD

**Issue by Hedgehog0** [codemann8/alttpr_codetracker_codemann8#29]
Hi,
Lastly when i enter the spectacle cave from the topmost door the check get validated in Emotracker even if i don't pick the item.

**Comment by codemann8** [comment]
Correct

**Comment by codemann8** [comment]
https://github.com/codemann8/alttpr_codetracker_codemann8/blob/746ab9d33e2f7ceeb9b95691ced697734ba80b94/README.md?plain=1#L115

**Comment by Hedgehog0** [comment]
Oh ok, thanks for the info
