### ISSUE TITLE
West Light World Death Mountain in Inverted

### ISSUE THREAD

**Issue by emerald000** [codemann8/alttpr_codetracker_codemann8#3]
In Inverted, the only access to West Light World Death Mountain is through the pegs bridge which requires both the Hammer and the Moon Pearl.

Currently, the tracker makes the region available without the moon pearl.

**Comment by codemann8** [comment]
Thank you. I actually noticed this issue when I played an Inverted ER seed the other day. I've made a fix to this and will be in the next release.
