### ISSUE TITLE
Paradox Cave Shop - Inverted Run

### ISSUE THREAD

**Issue by Hedgehog0** [codemann8/alttpr_codetracker_codemann8#30]
Hi,

I'm in an inverted run and shopsanity . I don't have the moon pearl yet. The tracker think that i can go in the Paradox Cave Shop but it's blocked by a bombable wall the problem is that I can't put bomb in bunny form (without glitch of course)

**Comment by Hedgehog0** [comment]
My actual Tracker state if needed :
![image](https://user-images.githubusercontent.com/67782107/179296745-835e8dd5-6d93-47f2-95ce-2f05108607d2.png)

**Comment by codemann8** [comment]
Good catch, already fixed and I'll likely push out an update soon. In the meantime, I recommend joining the Discord, linked in the other issue that's left open. It has a lot more eyes to look at an issue than it does here.
