### ISSUE TITLE
Turtle Rock mirror entrances in Inverted

### ISSUE THREAD

**Issue by emerald000** [codemann8/alttpr_codetracker_codemann8#5]
You do not need the pearl to enter Turtle Rock through the mirror entrances in Inverted. You can use the dark rocks warp in East Death Mountain, climb through Paradox Cave as a bunny, jump down and mirror.

**Comment by codemann8** [comment]
Fixed

**Comment by codemann8** [comment]
#

**Comment by codemann8** [comment]
@emerald000 I replaced the 2.0.1.4 release zip to include this change, please re-download
