### ISSUE TITLE
Improper Tracking in Inverted Entrance Shuffle

### ISSUE THREAD

**Issue by MarcyAugust** [codemann8/alttpr_codetracker_codemann8#7]
![codetracker bug inverted entrance shuffle](https://user-images.githubusercontent.com/51036202/92540976-a1af6a80-f1f9-11ea-9c97-fcd6eb355d98.PNG)

In Inverted Entrance Shuffle, entrances are not properly tracked as being accessible. Hyrule Castle is said to be almost entirely in logic, link's house (bomb shop) is not considered in logic, and a few other oddities as shown in the picture.

**Comment by codemann8** [comment]
In Inverted ER, you are not guaranteed access to any area since starting at Link's House can start you in the DW (or LW) in any entrance, when you find out which entrance is Link's you right click to clear it and the appropriate in-logic entrances will be shown green from there.
